---
driver:
  name: "terraform"
  root_module_directory: "examples/test_fixtures"

provisioner:
  name: "terraform"

platforms:
  - name: "aws"

verifier:
  name: "awspec"

suites:
  - name: "default"
    verifier:
      name: "awspec"
      patterns:
      - "test/integration/default/local_vpc.rb"
